apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: todonodejs
    name: route-frontend
  name: frontend
  namespace: mysql
spec:
  host: ocp4acm.apps.ocp4acm.sandbox549.opentlc.com
  path: "/todo"
  to:
    kind: Service
    name: frontend
    weight: 100
  wildcardPolicy: None
